% guidance_simulation.m
% Auto-generated by Multi-Agent System: 2026-04-07T14:43:07.225060
% Navigation Coefficient: 0.3847395463603973, Damping Ratio: 0.4274928804424135

function [miss_distance, control_energy, trajectory] = guidance_simulation()
    %% Simulation Parameters
    dt = 0.01;                    % Time step
    t_final = 100.0;         % Simulation duration
    time = 0:dt:t_final;
    n_steps = length(time);
    
    %% Target Parameters
    target_x = 10.0;
    target_y = 0.0;
    
    %% Guidance Parameters
    nav_coeff = 0.3847395463603973;      % Navigation coefficient
    damping_ratio = 0.4274928804424135;    % Damping ratio
    
    %% Initial Conditions
    x = 0.0; y = 0.0;           % Position
    vx = 1.0; vy = 0.0;       % Velocity
    ax = 0; ay = 0;                       % Acceleration
    
    %% Storage arrays
    trajectory = zeros(n_steps, 6);
    trajectory(1,:) = [x, y, vx, vy, ax, ay];
    
    %% Simulation Loop
    for i = 2:n_steps
        %% Current state
        pos = [x, y];
        vel = [vx, vy];
        
        %% Relative position to target
        rel_pos = [target_x - x, target_y - y];
        rel_vel = [0 - vx, 0 - vy];  % Target assumed stationary
        
        %% Time-to-go (proportional navigation)
        range = norm(rel_pos);
        t_go = range / (norm(rel_vel) + 1e-6);
        
        %% Navigation law: commanded acceleration
        if t_go > 0.1
            N = nav_coeff * ones(2,1);  % Navigation gain
            acc_cmd = N .* rel_vel / t_go;
        else
            acc_cmd = [0; 0];
        end
        
        %% Damping force
        damping_force = -damping_ratio * vel;
        
        %% Total acceleration
        ax = acc_cmd(1) + damping_force(1);
        ay = acc_cmd(2) + damping_force(2);
        
        %% Update state (Euler integration)
        x = x + vx * dt;
        y = y + vy * dt;
        vx = vx + ax * dt;
        vy = vy + ay * dt;
        
        %% Store trajectory
        trajectory(i,:) = [x, y, vx, vy, ax, ay];
    end
    
    %% Calculate Metrics
    final_pos = trajectory(end, 1:2);
    final_vel = trajectory(end, 3:4);
    
    miss_distance = norm(final_pos - [target_x, target_y]);
    
    control_energy = sum(sum(trajectory(:,5:6).^2)) * dt;
    
    fprintf('Simulation Complete\n');
    fprintf('Miss Distance: %.6f m\n', miss_distance);
    fprintf('Control Energy: %.6f J\n', control_energy);
end
