% optimize_guidance.m
% Auto-generated by Multi-Agent System: 2026-04-07T14:43:07.225060
% Optimization Script for Guidance Parameters

function [best_params, best_metrics] = optimize_guidance()
    %% Parameter Ranges
    nav_range = [0.3, 0.7];
    damp_range = [0.2, 0.5];
    
    %% Objectives: 'miss_distance', 'control_energy', 'overshoot'
    objectives = {'miss_distance'};
    
    %% Optimization options
    options = optimoptions('ga', ...
        'PopulationSize', 50, ...
        'MaxGenerations', 30, ...
        'CrossoverFraction', 0.8, ...
        'Display', 'iter');
    
    %% Objective function
    fitnessfcn = @(params) evaluate_params(params);
    
    %% Variable bounds: [nav_coeff, damping_ratio]
    lb = [nav_range(1), damp_range(1)];
    ub = [nav_range(2), damp_range(2)];
    
    %% Run Genetic Algorithm
    [best_params, ~] = ga(fitnessfcn, 2, [], [], [], [], lb, ub, [], options);
    
    %% Evaluate best parameters
    [miss_dist, ctrl_energy, ~] = evaluate_params(best_params);
    
    best_metrics = struct();
    best_metrics.navigation_coefficient = best_params(1);
    best_metrics.damping_ratio = best_params(2);
    best_metrics.miss_distance = miss_dist;
    best_metrics.control_energy = ctrl_energy;
    
    fprintf('\nOptimization Complete\n');
    fprintf('Best Navigation Coefficient: %.4f\n', best_params(1));
    fprintf('Best Damping Ratio: %.4f\n', best_params(2));
    fprintf('Best Miss Distance: %.6f m\n', miss_dist);
    fprintf('Best Control Energy: %.6f J\n', ctrl_energy);
end

function [miss_dist, ctrl_energy, traj] = evaluate_params(params)
    nav_coeff = params(1);
    damping = params(2);
    
    %% Run simulation with given parameters
    sim_params = struct();
    sim_params.navigation_coefficient = nav_coeff;
    sim_params.damping_ratio = damping;
    sim_params.target_position = [10, 0];
    sim_params.initial_position = [0, 0];
    sim_params.initial_velocity = [1, 0];
    
    [traj, metrics] = run_simulation(sim_params);
    
    miss_dist = metrics.miss_distance;
    ctrl_energy = metrics.control_energy;
end

function [trajectory, metrics] = run_simulation(params)
    %% Inline simulation (same as guidance_simulation.m)
    dt = 0.01;
    t_final = 100;
    time = 0:dt:t_final;
    n_steps = length(time);
    
    target_x = params.target_position(1);
    target_y = params.target_position(2);
    
    x = params.initial_position(1);
    y = params.initial_position(2);
    vx = params.initial_velocity(1);
    vy = params.initial_velocity(2);
    
    trajectory = zeros(n_steps, 6);
    trajectory(1,:) = [x, y, vx, vy, 0, 0];
    
    for i = 2:n_steps
        rel_pos = [target_x - x, target_y - y];
        rel_vel = [0 - vx, 0 - vy];
        range = norm(rel_pos);
        t_go = range / (norm(rel_vel) + 1e-6);
        
        if t_go > 0.1
            acc_cmd = params.navigation_coefficient * rel_vel / t_go;
        else
            acc_cmd = [0; 0];
        end
        
        damping_force = -params.damping_ratio * [vx, vy];
        ax = acc_cmd(1) + damping_force(1);
        ay = acc_cmd(2) + damping_force(2);
        
        x = x + vx * dt;
        y = y + vy * dt;
        vx = vx + ax * dt;
        vy = vy + ay * dt;
        
        trajectory(i,:) = [x, y, vx, vy, ax, ay];
    end
    
    miss_dist = norm([x, y] - [target_x, target_y]);
    ctrl_energy = sum(sum(trajectory(:,5:6).^2)) * dt;
    
    metrics = struct('miss_distance', miss_dist, 'control_energy', ctrl_energy);
end
