#!/usr/bin/env python3
"""
Guidance System Simulation Module
自动生成 SysML 模型和 MATLAB/Simulink 脚本进行迭代模拟验证
"""

import os
import json
import logging
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from datetime import datetime
import asyncio

logger = logging.getLogger(__name__)


@dataclass
class GuidanceParameters:
    """制导系统参数"""

    navigation_coefficient: float = 3.0
    damping_ratio: float = 0.3
    control_gain: float = 1.0
    target_position: List[float] = field(default_factory=lambda: [20000.0, 2000.0, 5000.0])
    target_velocity: List[float] = field(default_factory=lambda: [250.0, 0.0, 0.0])
    target_velocity_expr: List[str] = field(default_factory=lambda: ["250.0", "0.0", "0.0"])
    initial_position: List[float] = field(default_factory=lambda: [0.0, 7000.0, 0.0])
    initial_velocity: List[float] = field(default_factory=lambda: [960.0, 0.0, 0.0])
    initial_angles: List[float] = field(default_factory=lambda: [0.0, 0.0, 0.0]) # upsilon, phi, gama
    gama_max: float = 45.0
    scenario_id: int = 2 # 默认使用工况2（标准基准工况）

    def to_dict(self) -> Dict[str, Any]:
        return {
            "navigation_coefficient": self.navigation_coefficient,
            "damping_ratio": self.damping_ratio,
            "control_gain": self.control_gain,
            "target_position": self.target_position,
            "target_velocity": self.target_velocity,
            "target_velocity_expr": self.target_velocity_expr,
            "initial_position": self.initial_position,
            "initial_velocity": self.initial_velocity,
            "initial_angles": self.initial_angles,
            "gama_max": self.gama_max,
            "scenario_id": self.scenario_id,
        }


@dataclass
class SimulationResult:
    """仿真结果"""

    miss_distance: float
    control_energy: float
    max_overshoot: float
    settling_time: float
    final_position: List[float]
    final_velocity: List[float]
    trajectory: List[Dict[str, float]]
    execution_time: float
    success: bool = True
    error: Optional[str] = None


class SysMLModelGenerator:
    """SysML 模型生成器"""

    def __init__(self, output_dir: str = "./sysml_models"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        
        # Reference template directory
        self.kb_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
            "knowledge_base", "sysml"
        )

    def _read_template(self, filename: str, fallback: str) -> str:
        filepath = os.path.join(self.kb_dir, filename)
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                return f.read()
        except FileNotFoundError:
            logger.warning(f"SysML reference template not found at {filepath}, using fallback.")
            return fallback

    def generate_block_definition_diagram(
        self, params: GuidanceParameters, model_name: str = "GuidanceSystem"
    ) -> str:
        """生成 SysML Block Definition Diagram (BDD)"""

        fallback = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Multi-Agent System: {datetime.now().isoformat()} -->
<SysML xmlns="http://www.omg.org/spec/SysML/20190109/SysML">
  <package name="{{model_name}}">
    <block name="GuidanceController" isAbstract="false">
      <ownedAttribute name="navigationCoefficient" type="Real" multiplicity="1">
        <defaultValue value="{{navigation_coefficient}}"/>
      </ownedAttribute>
      <ownedAttribute name="dampingRatio" type="Real" multiplicity="1">
        <defaultValue value="{{damping_ratio}}"/>
      </ownedAttribute>
    </block>
    <block name="Autopilot">
      <ownedAttribute name="controlGain" type="Real" multiplicity="1">
        <defaultValue value="{{control_gain}}"/>
      </ownedAttribute>
      <operation name="three_loop_autopilot"/>
    </block>
  </package>
</SysML>"""

        template = self._read_template("sysml_bdd_reference.xml", fallback)
        return template.format(
            model_name=model_name,
            navigation_coefficient=params.navigation_coefficient,
            damping_ratio=params.damping_ratio,
            control_gain=params.control_gain,
        )

    def generate_parametric_diagram(
        self, params: GuidanceParameters, model_name: str = "GuidanceSystem"
    ) -> str:
        """生成 SysML Parametric Diagram"""

        fallback = f"""<?xml version="1.0" encoding="UTF-8"?>
<SysML xmlns="http://www.omg.org/spec/SysML/20190109/SysML">
  <block name="GuidanceEquations">
    <constraint name="navigationEquation">
      <ownedAttribute name="N" type="Real" value="{{navigation_coefficient}}"/>
    </constraint>
    <constraint name="dampingEquation">
      <ownedAttribute name="c" type="Real" value="{{damping_ratio}}"/>
    </constraint>
    <constraint name="missDistanceEquation">
      <ownedAttribute name="targetPosition" type="Vector3D" value="({{target_position_0}}, {{target_position_1}}, {{target_position_2}})"/>
    </constraint>
  </block>
</SysML>"""

        template = self._read_template("sysml_parametric_reference.xml", fallback)
        return template.format(
            model_name=model_name,
            navigation_coefficient=params.navigation_coefficient,
            damping_ratio=params.damping_ratio,
            target_position_0=params.target_position[0],
            target_position_1=params.target_position[1],
            target_position_2=params.target_position[2],
        )

    def generate_internal_block_diagram(
        self, params: GuidanceParameters, model_name: str = "GuidanceSystem"
    ) -> str:
        """生成 SysML Internal Block Diagram (IBD)"""

        fallback = f"""<?xml version="1.0" encoding="UTF-8"?>
<SysML xmlns="http://www.omg.org/spec/SysML/20190109/SysML">
  <block name="InterceptorAssembly">
    <part name="sensor" type="TargetTracker"/>
    <part name="guidance" type="GuidanceController"/>
  </block>
</SysML>"""

        template = self._read_template("sysml_ibd_reference.xml", fallback)
        return template.format(
            model_name=model_name,
        )

    def save_model(
        self, params: GuidanceParameters, model_name: str = "GuidanceSystem"
    ) -> Dict[str, str]:
        """生成并保存完整的 SysML 模型"""

        files = {
            f"{model_name}_bdd.xml": self.generate_block_definition_diagram(params, model_name),
            f"{model_name}_parametric.xml": self.generate_parametric_diagram(params, model_name),
            f"{model_name}_ibd.xml": self.generate_internal_block_diagram(params, model_name),
        }

        saved_files = {}
        for filename, content in files.items():
            filepath = os.path.join(self.output_dir, filename)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            saved_files[filename] = filepath
            logger.info(f"Generated SysML file: {filepath}")

        return saved_files


class MATLABScriptGenerator:
    """MATLAB 脚本生成器"""

    def __init__(self, output_dir: str = "./matlab_scripts"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_simulation_script(
        self,
        params: GuidanceParameters,
        duration: float = 100.0,
        dt: float = 0.01,
        script_name: str = "guidance_simulation.m",
    ) -> str:
        """生成 MATLAB 仿真脚本 (6-DOF)"""
        
        # 尝试读取知识库中的原始 6-DOF 模型
        base_script_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
            "knowledge_base", "matlab", "robust_analysis", "chengxu_robust_analysis_singlefile.m"
        )
        
        try:
            with open(base_script_path, "r", encoding="utf-8") as f:
                base_script = f.read()
        except FileNotFoundError:
            logger.error(f"Base MATLAB script not found at {base_script_path}")
            base_script = "% Error: Base script not found\n"
            
        # 根据 params 替换初始条件和目标运动
        
        # 替换参数
        init_x, init_y, init_z = params.initial_position
        init_v = params.initial_velocity[0] # 简化的初速提取
        init_upsilon, init_phi, init_gama = params.initial_angles
        gama_max = params.gama_max
        
        target_x, target_y, target_z = params.target_position
        target_vx, target_vy, target_vz = params.target_velocity_expr
        
        nav_coeff = params.navigation_coefficient
        damping = params.damping_ratio
        
        # 使用简单的字符串替换来更新初始条件
        # 注意: 实际项目中可能需要更复杂的正则表达式或 AST 解析
        
        # 修改制导律中的参数
        script = base_script.replace(
            "function chengxu_robust_analysis_singlefile", 
            f"function [miss_distance, control_energy, trajectory] = {script_name.replace('.m', '')}()"
        )
        
        # 替换目标运动 (简化版替换，针对不同工况可能需要定制)
        script = script.replace(
            "T_x=20000;T_y=2000;T_z=5000;",
            f"T_x={target_x};T_y={target_y};T_z={target_z};"
        )
        
        # 替换初始条件
        script = script.replace(
            "y=7000;x=0;z=0;V=960;",
            f"y={init_y};x={init_x};z={init_z};V={init_v};"
        )
        script = script.replace(
            "upsilon=-0/C45;gama=0/C45;phi=0/C45;theta=-0/C45;phiv=0;",
            f"upsilon={init_upsilon}/C45;gama={init_gama}/C45;phi={init_phi}/C45;theta={init_upsilon}/C45;phiv={init_phi};"
        )
        script = script.replace(
            "gama_max=45/C45;",
            f"gama_max={gama_max}/C45;"
        )
        
        # 替换目标速度 (假设目标运动在 matlab 脚本中为 T_Vx=250;T_Vy=50;T_Vz=50*cos(0.2*t);)
        script = script.replace(
            "T_Vx=250;T_Vy=50;T_Vz=50*cos(0.2*t);",
            f"T_Vx={target_vx};T_Vy={target_vy};T_Vz={target_vz};"
        )
        
        script = script.replace(
            "T_Vx_end = 250;\n    T_Vy_end = 50;\n    T_Vz_end = 50*cos(0.2*t);",
            f"T_Vx_end = {target_vx};\n    T_Vy_end = {target_vy};\n    T_Vz_end = {target_vz};"
        )
        script = script.replace(
            "T_Vx_end = 250;\nT_Vy_end = 50;\nT_Vz_end = 50*cos(0.2*t);",
            f"T_Vx_end = {target_vx};\nT_Vy_end = {target_vy};\nT_Vz_end = {target_vz};"
        )
        
        # 注入 nav_coeff 和 damping_ratio 到 global 变量或直接替换
        # 这里为了简化，我们在 guidance_local 中直接使用这些参数
        script = script.replace(
            "ayc_A=3*sqrt(Vrx^2+Vry^2)*qz_dot;",
            f"ayc_A={nav_coeff}*sqrt(Vrx^2+Vry^2)*qz_dot - {damping}*Vy_A;"
        )
        script = script.replace(
            "azc_A=-3*sqrt(Vrx^2+Vrz^2)*qy_dot;",
            f"azc_A=-{nav_coeff}*sqrt(Vrx^2+Vrz^2)*qy_dot + {damping}*Vz_A;"
        )
        
        # 确保输出格式兼容现有的解析逻辑
        script += """
% --- Generated output for parser ---
function dump_metrics(miss_min, Ju)
    fprintf('Simulation Complete\\n');
    fprintf('Miss Distance: %.6f m\\n', miss_min);
    fprintf('Control Energy: %.6f J\\n', Ju);
end
"""
        script = script.replace(
            "fprintf('==========================================\\n');",
            "fprintf('==========================================\\n');\ndump_metrics(timeMetrics.miss_min, timeMetrics.Ju);\nmiss_distance = timeMetrics.miss_min;\ncontrol_energy = timeMetrics.Ju;\ntrajectory = Track;\n"
        )
        
        return script

    def generate_optimization_script(
        self,
        param_ranges: Dict[str, Tuple[float, float]],
        objectives: List[str],
        script_name: str = "optimize_guidance.m",
    ) -> str:
        """生成 MATLAB 优化脚本"""

        nav_range = param_ranges.get("navigation_coefficient", (0.3, 0.8))
        damp_range = param_ranges.get("damping_ratio", (0.2, 0.5))

        script = f"""% optimize_guidance.m
% Auto-generated by Multi-Agent System: {datetime.now().isoformat()}
% Optimization Script for Guidance Parameters

function [best_params, best_metrics] = optimize_guidance()
    %% Parameter Ranges
    nav_range = [{nav_range[0]}, {nav_range[1]}];
    damp_range = [{damp_range[0]}, {damp_range[1]}];
    
    %% Objectives: 'miss_distance', 'control_energy', 'overshoot'
    objectives = {{'{objectives[0] if objectives else "miss_distance"}'}};
    
    %% Optimization options
    options = optimoptions('ga', ...
        'PopulationSize', 50, ...
        'MaxGenerations', 30, ...
        'CrossoverFraction', 0.8, ...
        'Display', 'iter');
    
    %% Objective function
    fitnessfcn = @(params) evaluate_params(params);
    
    %% Variable bounds: [nav_coeff, damping_ratio]
    lb = [nav_range(1), damp_range(1)];
    ub = [nav_range(2), damp_range(2)];
    
    %% Run Genetic Algorithm
    [best_params, ~] = ga(fitnessfcn, 2, [], [], [], [], lb, ub, [], options);
    
    %% Evaluate best parameters
    [miss_dist, ctrl_energy, ~] = evaluate_params(best_params);
    
    best_metrics = struct();
    best_metrics.navigation_coefficient = best_params(1);
    best_metrics.damping_ratio = best_params(2);
    best_metrics.miss_distance = miss_dist;
    best_metrics.control_energy = ctrl_energy;
    
    fprintf('\\nOptimization Complete\\n');
    fprintf('Best Navigation Coefficient: %.4f\\n', best_params(1));
    fprintf('Best Damping Ratio: %.4f\\n', best_params(2));
    fprintf('Best Miss Distance: %.6f m\\n', miss_dist);
    fprintf('Best Control Energy: %.6f J\\n', ctrl_energy);
end

function [miss_dist, ctrl_energy, traj] = evaluate_params(params)
    nav_coeff = params(1);
    damping = params(2);
    
    %% Run simulation with given parameters
    sim_params = struct();
    sim_params.navigation_coefficient = nav_coeff;
    sim_params.damping_ratio = damping;
    sim_params.target_position = [10, 0];
    sim_params.initial_position = [0, 0];
    sim_params.initial_velocity = [1, 0];
    
    [traj, metrics] = run_simulation(sim_params);
    
    miss_dist = metrics.miss_distance;
    ctrl_energy = metrics.control_energy;
end

function [trajectory, metrics] = run_simulation(params)
    %% Inline simulation (same as guidance_simulation.m)
    dt = 0.01;
    t_final = 100;
    time = 0:dt:t_final;
    n_steps = length(time);
    
    target_x = params.target_position(1);
    target_y = params.target_position(2);
    
    x = params.initial_position(1);
    y = params.initial_position(2);
    vx = params.initial_velocity(1);
    vy = params.initial_velocity(2);
    
    trajectory = zeros(n_steps, 6);
    trajectory(1,:) = [x, y, vx, vy, 0, 0];
    
    for i = 2:n_steps
        rel_pos = [target_x - x, target_y - y];
        rel_vel = [0 - vx, 0 - vy];
        range = norm(rel_pos);
        t_go = range / (norm(rel_vel) + 1e-6);
        
        if t_go > 0.1
            acc_cmd = params.navigation_coefficient * rel_vel / t_go;
        else
            acc_cmd = [0; 0];
        end
        
        damping_force = -params.damping_ratio * [vx, vy];
        ax = acc_cmd(1) + damping_force(1);
        ay = acc_cmd(2) + damping_force(2);
        
        x = x + vx * dt;
        y = y + vy * dt;
        vx = vx + ax * dt;
        vy = vy + ay * dt;
        
        trajectory(i,:) = [x, y, vx, vy, ax, ay];
    end
    
    miss_dist = norm([x, y] - [target_x, target_y]);
    ctrl_energy = sum(sum(trajectory(:,5:6).^2)) * dt;
    
    metrics = struct('miss_distance', miss_dist, 'control_energy', ctrl_energy);
end
"""
        return script

    def save_scripts(
        self,
        params: GuidanceParameters,
        duration: float = 100.0,
        dt: float = 0.01,
        param_ranges: Optional[Dict[str, Tuple[float, float]]] = None,
        objectives: Optional[List[str]] = None,
    ) -> Dict[str, str]:
        """生成并保存 MATLAB 脚本"""

        scripts = {
            "guidance_simulation.m": self.generate_simulation_script(params, duration, dt),
        }

        if param_ranges:
            scripts["optimize_guidance.m"] = self.generate_optimization_script(
                param_ranges, objectives or ["miss_distance"]
            )

        saved_files = {}
        for filename, content in scripts.items():
            filepath = os.path.join(self.output_dir, filename)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            saved_files[filename] = filepath
            logger.info(f"Generated MATLAB script: {filepath}")

        return saved_files


class SimulationExecutor:
    """仿真执行器，支持 Python / Octave / MATLAB"""

    def __init__(
        self,
        engine: str = "octave",  # "python" | "octave" | "matlab"
        octave_path: str = "octave",
        matlab_path: str = "matlab",
        output_dir: str = "./simulation_results",
    ):
        self.engine = engine
        self.octave_path = octave_path
        self.matlab_path = matlab_path
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    async def run_simulation(
        self,
        params: GuidanceParameters,
        duration: float = 100.0,
        dt: float = 0.01,
        script_path: Optional[str] = None,
    ) -> SimulationResult:
        """执行仿真（根据配置的引擎）"""

        start_time = asyncio.get_event_loop().time()

        try:
            if self.engine == "python":
                result = await self._python_simulation(params, duration, dt)
            elif self.engine in ["octave", "matlab"] and script_path:
                result = await self.run_external_simulation(script_path)
            else:
                result = await self._python_simulation(params, duration, dt)
            result.execution_time = asyncio.get_event_loop().time() - start_time
            return result
        except Exception as e:
            logger.error(f"Simulation failed: {e}")
            return SimulationResult(
                miss_distance=0,
                control_energy=0,
                max_overshoot=0,
                settling_time=0,
                final_position=[0, 0],
                final_velocity=[0, 0],
                trajectory=[],
                execution_time=0,
                success=False,
                error=str(e),
            )

    async def _python_simulation(
        self,
        params: GuidanceParameters,
        duration: float,
        dt: float,
    ) -> SimulationResult:
        """使用 Python 进行 3D 制导仿真计算"""

        nav_coeff = params.navigation_coefficient
        damping = params.damping_ratio
        
        target_x, target_y, target_z = params.target_position
        target_vx, target_vy, target_vz = params.target_velocity

        x, y, z = params.initial_position
        vx, vy, vz = params.initial_velocity

        trajectory = []
        control_energies = []

        num_steps = int(duration / dt)
        
        # 简单模拟 3D 运动
        for step in range(num_steps):
            current_time = step * dt
            trajectory.append(
                {"x": x, "y": y, "z": z, "vx": vx, "vy": vy, "vz": vz, "ax": 0, "ay": 0, "az": 0, "time": current_time}
            )

            rel_pos = [target_x - x, target_y - y, target_z - z]
            rel_vel = [target_vx - vx, target_vy - vy, target_vz - vz]
            range_to_target = (rel_pos[0] ** 2 + rel_pos[1] ** 2 + rel_pos[2] ** 2) ** 0.5
            v_close = -((rel_pos[0]*rel_vel[0] + rel_pos[1]*rel_vel[1] + rel_pos[2]*rel_vel[2]) / (range_to_target + 1e-6))
            
            t_go = range_to_target / (v_close + 1e-6) if v_close > 0 else 999.0

            if t_go > 0.1 and range_to_target > 5.0 and v_close > 0:
                # 3D 比例导引律
                omega_x = (rel_pos[1]*rel_vel[2] - rel_pos[2]*rel_vel[1]) / (range_to_target**2 + 1e-6)
                omega_y = (rel_pos[2]*rel_vel[0] - rel_pos[0]*rel_vel[2]) / (range_to_target**2 + 1e-6)
                omega_z = (rel_pos[0]*rel_vel[1] - rel_pos[1]*rel_vel[0]) / (range_to_target**2 + 1e-6)
                
                acc_cmd_x = nav_coeff * v_close * (omega_y * rel_pos[2] - omega_z * rel_pos[1]) / (range_to_target + 1e-6)
                acc_cmd_y = nav_coeff * v_close * (omega_z * rel_pos[0] - omega_x * rel_pos[2]) / (range_to_target + 1e-6)
                acc_cmd_z = nav_coeff * v_close * (omega_x * rel_pos[1] - omega_y * rel_pos[0]) / (range_to_target + 1e-6)
            else:
                acc_cmd_x = acc_cmd_y = acc_cmd_z = 0.0

            damping_force = [-damping * vx, -damping * vy, -damping * vz]
            ax = acc_cmd_x + damping_force[0]
            ay = acc_cmd_y + damping_force[1]
            az = acc_cmd_z + damping_force[2]

            control_energies.append(ax**2 + ay**2 + az**2)

            x = x + vx * dt
            y = y + vy * dt
            z = z + vz * dt
            vx = vx + ax * dt
            vy = vy + ay * dt
            vz = vz + az * dt
            
            # 更新目标位置 (匀速直线运动，复杂机动可在后续细化)
            target_x += target_vx * dt
            target_y += target_vy * dt
            target_z += target_vz * dt

        miss_distance = ((x - target_x) ** 2 + (y - target_y) ** 2 + (z - target_z) ** 2) ** 0.5
        control_energy = sum(control_energies) * dt

        positions = [t["y"] for t in trajectory]
        max_overshoot = max(abs(max(positions) - target_y), abs(min(positions))) if positions else 0

        settling_idx = len(trajectory) - 1
        for i, t in enumerate(trajectory):
            if abs(t["y"] - target_y) > 0.05:
                settling_idx = i
        settling_time = settling_idx * dt

        return SimulationResult(
            miss_distance=miss_distance,
            control_energy=control_energy,
            max_overshoot=max_overshoot,
            settling_time=settling_time,
            final_position=[x, y, z],
            final_velocity=[vx, vy, vz],
            trajectory=trajectory,
            execution_time=0,
            success=True,
        )

    async def run_external_simulation(
        self,
        script_path: str,
    ) -> SimulationResult:
        """使用 Octave 或 MATLAB 执行 .m 脚本"""

        if not os.path.exists(script_path):
            return SimulationResult(
                miss_distance=0,
                control_energy=0,
                max_overshoot=0,
                settling_time=0,
                final_position=[0, 0],
                final_velocity=[0, 0],
                trajectory=[],
                execution_time=0,
                success=False,
                error=f"Script not found: {script_path}",
            )

        try:
            import subprocess

            if self.engine == "octave":
                cmd = [self.octave_path, "--quiet", "--eval", f"run('{script_path}')"]
                exe_name = "Octave"
            elif self.engine == "matlab":
                cmd = [self.matlab_path, "-batch", f"run('{script_path}')"]
                exe_name = "MATLAB"
            else:
                return SimulationResult(
                    miss_distance=0,
                    control_energy=0,
                    max_overshoot=0,
                    settling_time=0,
                    final_position=[0, 0],
                    final_velocity=[0, 0],
                    trajectory=[],
                    execution_time=0,
                    success=False,
                    error=f"Unsupported engine: {self.engine}",
                )

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300,
            )

            if result.returncode != 0:
                return SimulationResult(
                    miss_distance=0,
                    control_energy=0,
                    max_overshoot=0,
                    settling_time=0,
                    final_position=[0, 0],
                    final_velocity=[0, 0],
                    trajectory=[],
                    execution_time=0,
                    success=False,
                    error=f"{exe_name} error: {result.stderr}",
                )

            # Parse output for metrics
            return self._parse_external_output(result.stdout)

        except FileNotFoundError:
            logger.warning(f"{self.engine} not found, falling back to Python")
            return await self._python_simulation(GuidanceParameters(), 100.0, 0.01)
        except Exception as e:
            logger.error(f"{self.engine} execution failed: {e}")
            return SimulationResult(
                miss_distance=0,
                control_energy=0,
                max_overshoot=0,
                settling_time=0,
                final_position=[0, 0],
                final_velocity=[0, 0],
                trajectory=[],
                execution_time=0,
                success=False,
                error=str(e),
            )

    def _parse_external_output(self, stdout: str) -> SimulationResult:
        """解析 Octave/MATLAB 输出来提取指标"""
        miss_distance = 0.0
        control_energy = 0.0
        success = False

        for line in stdout.split('\n'):
            line = line.strip().lower()
            if 'miss distance' in line or 'miss_distance' in line:
                parts = line.split()
                for i, p in enumerate(parts):
                    try:
                        if p.replace('.', '').replace('-', '').isdigit():
                            miss_distance = float(p)
                            success = True
                            break
                    except ValueError:
                        continue
            elif 'control energy' in line or 'control_energy' in line:
                parts = line.split()
                for i, p in enumerate(parts):
                    try:
                        if p.replace('.', '').replace('-', '').isdigit():
                            control_energy = float(p)
                            break
                    except ValueError:
                        continue

        return SimulationResult(
            miss_distance=miss_distance,
            control_energy=control_energy,
            max_overshoot=0.0,
            settling_time=0.0,
            final_position=[0, 0],
            final_velocity=[0, 0],
            trajectory=[],
            execution_time=0.0,
            success=success,
        )


class GuidanceSimulator:
    """
    制导系统仿真器
    整合 SysML 模型生成、MATLAB 脚本生成、仿真执行
    """

    def __init__(
        self,
        output_dir: str = "./guidance_workspace",
        engine: str = "octave",  # "python" | "octave" | "matlab"
        octave_path: str = "octave",
        matlab_path: str = "matlab",
    ):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

        self.sysml_dir = os.path.join(output_dir, "sysml_models")
        self.matlab_dir = os.path.join(output_dir, "matlab_scripts")
        self.results_dir = os.path.join(output_dir, "results")

        for d in [self.sysml_dir, self.matlab_dir, self.results_dir]:
            os.makedirs(d, exist_ok=True)

        self.sysml_generator = SysMLModelGenerator(self.sysml_dir)
        self.matlab_generator = MATLABScriptGenerator(self.matlab_dir)
        self.executor = SimulationExecutor(
            engine=engine,
            octave_path=octave_path,
            matlab_path=matlab_path,
            output_dir=self.results_dir,
        )

    async def generate_and_simulate(
        self,
        params: GuidanceParameters,
        duration: float = 100.0,
        dt: float = 0.01,
        param_ranges: Optional[Dict[str, Tuple[float, float]]] = None,
        objectives: Optional[List[str]] = None,
        generate_sysml: bool = True,
        generate_matlab: bool = True,
    ) -> Dict[str, Any]:
        """
        完整的生成-仿真流程

        1. 生成 SysML 模型
        2. 生成 MATLAB 脚本
        3. 执行仿真
        4. 返回结果
        """

        results = {
            "timestamp": datetime.now().isoformat(),
            "parameters": params.to_dict(),
            "simulation_config": {"duration": duration, "dt": dt},
            "generated_files": {},
            "simulation_result": None,
        }

        if generate_sysml:
            sysml_files = self.sysml_generator.save_model(params)
            results["generated_files"]["sysml"] = sysml_files

        script_path = None
        if generate_matlab:
            matlab_files = self.matlab_generator.save_scripts(
                params, duration, dt, param_ranges, objectives
            )
            results["generated_files"]["matlab"] = matlab_files
            script_path = matlab_files.get("guidance_simulation.m")

        sim_result = await self.executor.run_simulation(params, duration, dt, script_path)
        results["simulation_result"] = {
            "miss_distance": sim_result.miss_distance,
            "control_energy": sim_result.control_energy,
            "max_overshoot": sim_result.max_overshoot,
            "settling_time": sim_result.settling_time,
            "final_position": sim_result.final_position,
            "execution_time": sim_result.execution_time,
            "success": sim_result.success,
            "error": sim_result.error,
        }

        results_file = os.path.join(
            self.results_dir, f"result_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        )
        with open(results_file, "w") as f:
            json.dump(results, f, indent=2)

        logger.info(f"Simulation complete. Results saved to: {results_file}")

        return results

    async def parameter_study(
        self,
        param_grid: Dict[str, List[float]],
        duration: float = 100.0,
        dt: float = 0.01,
    ) -> List[Dict[str, Any]]:
        """
        参数研究：遍历参数网格，评估所有组合
        """
        import itertools

        keys = list(param_grid.keys())
        values = list(param_grid.values())
        combinations = list(itertools.product(*values))

        results = []
        for combo in combinations:
            params_dict = dict(zip(keys, combo))
            params = GuidanceParameters(**params_dict)

            result = await self.generate_and_simulate(params, duration, dt)
            results.append(
                {
                    "parameters": params_dict,
                    "metrics": result["simulation_result"],
                }
            )

        return results

    async def rl_optimize(
        self,
        initial_params: GuidanceParameters,
        param_bounds: Dict[str, Tuple[float, float]],
        episodes: int = 50,
        max_steps_per_episode: int = 20,
        duration: float = 100.0,
        dt: float = 0.01,
        energy_constraint: float = 0.2,
        target_miss_distance: float = 1.0,
    ) -> Dict[str, Any]:
        """
        使用强化学习优化导引系统参数

        Args:
            initial_params: 初始参数
            param_bounds: 参数边界 {param_name: (min, max)}
            episodes: 训练回合数
            max_steps_per_episode: 每回合最大步数
            duration: 仿真时长
            dt: 时间步长
            energy_constraint: 控制能量约束
            target_miss_distance: 目标脱靶量

        Returns:
            优化结果，包含最优参数和训练历史
        """
        from ..rl.reinforcement_learner import ReinforcementLearner, RLConfig, RLAlgorithm

        rl_config = RLConfig(
            algorithm=RLAlgorithm.DQN,
            learning_rate=0.001,
            discount_factor=0.95,
            epsilon=0.3,
            epsilon_decay=0.98,
            epsilon_min=0.01,
            batch_size=16,
            target_update_freq=10,
            memory_capacity=5000,
        )

        learner = ReinforcementLearner(rl_config)
        learner.initialize(state_dim=6, action_dim=3)

        state_dim = 6
        action_dim = 3
        param_names = list(param_bounds.keys())
        param_dims = [
            len(param_bounds[k][0]) if isinstance(param_bounds[k][0], list) else 1
            for k in param_names
        ]

        all_rewards = []
        best_result = None
        best_reward = float("-inf")

        history = []

        for episode in range(episodes):
            episode_reward = 0.0
            episode_history = []

            current_params = GuidanceParameters(
                navigation_coefficient=initial_params.navigation_coefficient,
                damping_ratio=initial_params.damping_ratio,
                control_gain=initial_params.control_gain,
                target_position=initial_params.target_position.copy(),
                initial_position=initial_params.initial_position.copy(),
                initial_velocity=initial_params.initial_velocity.copy(),
            )

            state = self._params_to_state(current_params, best_result)

            for step in range(max_steps_per_episode):
                action_dict = await learner.select_action(state, iteration=episode)

                new_params, action_applied = self._apply_rl_action(
                    current_params, action_dict, param_bounds, param_names
                )

                sim_result = await self.executor.run_simulation(new_params, duration, dt)
                metrics = {
                    "miss_distance": sim_result.miss_distance,
                    "control_energy": sim_result.control_energy,
                    "max_overshoot": sim_result.max_overshoot,
                    "settling_time": sim_result.settling_time,
                }

                reward = self._compute_reward(metrics, energy_constraint, target_miss_distance)

                next_state = self._params_to_state(new_params, best_result)

                done = step == max_steps_per_episode - 1

                await learner.store_experience(
                    state=state,
                    action=action_dict,
                    reward=reward,
                    next_state=next_state,
                    done=done,
                )

                try:
                    train_result = await learner.train_step()
                    if train_result:
                        logger.debug(
                            f"Episode {episode}, Step {step}: loss={train_result['loss']:.4f}, epsilon={train_result['epsilon']:.3f}"
                        )
                except Exception as e:
                    logger.debug(f"Training step skipped: {e}")

                episode_reward += reward
                episode_history.append(
                    {
                        "step": step,
                        "params": new_params.to_dict(),
                        "metrics": metrics,
                        "reward": reward,
                    }
                )

                state = next_state
                current_params = new_params

                if reward > best_reward:
                    best_reward = reward
                    best_result = {
                        "parameters": new_params.to_dict(),
                        "metrics": metrics,
                        "episode": episode,
                        "step": step,
                    }

            all_rewards.append(episode_reward)
            history.append(
                {
                    "episode": episode,
                    "total_reward": episode_reward,
                    "best_params": current_params.to_dict(),
                    "best_metrics": episode_history[-1]["metrics"] if episode_history else None,
                }
            )

            logger.info(
                f"RL Episode {episode}/{episodes}: reward={episode_reward:.4f}, "
                f"best_reward={best_reward:.4f}, epsilon={learner._epsilon:.3f}"
            )

        return {
            "best_parameters": best_result["parameters"]
            if best_result
            else initial_params.to_dict(),
            "best_metrics": best_result["metrics"] if best_result else {},
            "training_history": history,
            "learner_stats": learner.get_statistics(),
        }

    def _params_to_state(
        self,
        params: GuidanceParameters,
        best_result: Optional[Dict[str, Any]],
    ) -> List[float]:
        """将参数转换为RL状态"""
        state = [
            params.navigation_coefficient,
            params.damping_ratio,
            params.control_gain,
            params.target_position[0]
            if best_result is None
            else best_result["metrics"].get("miss_distance", 5.0),
            params.target_position[1]
            if best_result is None
            else best_result["metrics"].get("control_energy", 0.15),
            0.0,
        ]
        return state

    def _apply_rl_action(
        self,
        params: GuidanceParameters,
        action_dict: Dict[str, float],
        param_bounds: Dict[str, Tuple[float, float]],
        param_names: List[str],
    ) -> Tuple[GuidanceParameters, str]:
        """应用RL动作到参数"""
        adjustments = {
            "navigation_coefficient": action_dict.get("param_0", 0.0),
            "damping_ratio": action_dict.get("param_1", 0.0),
            "control_gain": action_dict.get("param_2", 0.0),
        }

        nav_coeff = params.navigation_coefficient + adjustments["navigation_coefficient"] * 0.1
        nav_coeff = max(
            param_bounds["navigation_coefficient"][0],
            min(param_bounds["navigation_coefficient"][1], nav_coeff),
        )

        damping = params.damping_ratio + adjustments["damping_ratio"] * 0.05
        damping = max(
            param_bounds["damping_ratio"][0], min(param_bounds["damping_ratio"][1], damping)
        )

        control_gain = params.control_gain + adjustments["control_gain"] * 0.1
        control_gain = max(
            param_bounds["control_gain"][0], min(param_bounds["control_gain"][1], control_gain)
        )

        new_params = GuidanceParameters(
            navigation_coefficient=nav_coeff,
            damping_ratio=damping,
            control_gain=control_gain,
            target_position=params.target_position.copy(),
            initial_position=params.initial_position.copy(),
            initial_velocity=params.initial_velocity.copy(),
        )

        return new_params, f"nav={nav_coeff:.3f}, damp={damping:.3f}"

    def _compute_reward(
        self,
        metrics: Dict[str, float],
        energy_constraint: float,
        target_miss_distance: float,
    ) -> float:
        """计算奖励函数"""
        miss_distance = metrics["miss_distance"]
        control_energy = metrics["control_energy"]

        miss_reward = 10.0 / (1.0 + miss_distance)
        energy_penalty = 5.0 if control_energy > energy_constraint else 0.0
        target_reward = 20.0 if miss_distance < target_miss_distance else 0.0

        reward = miss_reward - energy_penalty + target_reward

        return reward
