import json
import logging
from typing import Dict, Any

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field

from multi_agent.config_loader import get_config

logger = logging.getLogger(__name__)

class ReflectionOutput(BaseModel):
    needs_optimization: bool = Field(description="是否需要进一步优化参数")
    suggestion: str = Field(description="给出的优化建议，如果不需要优化可以为空")

class ReflectionAgent:
    """
    结果反思智能体，基于 LangChain 实现。
    用于判别仿真结果，并给出优化建议。
    """
    
    def __init__(self):
        cfg = get_config().llm
        self.llm = ChatOpenAI(
            model=cfg.model,
            openai_api_key=cfg.api_key or "sk-dummy",
            openai_api_base=cfg.base_url,
            temperature=0.2
        )
        self.parser = JsonOutputParser(pydantic_object=ReflectionOutput)
        
        self.prompt = ChatPromptTemplate.from_messages([
            ("system", """你是一个仿真结果反思与判别专家。你需要根据当前的仿真结果（包括脱靶量和控制能量等指标），判断是否达到了要求，是否需要进一步优化参数。
通常，脱靶量 (Miss Distance) 越小越好（例如小于 1.0m 算作优秀），控制能量 (Control Energy) 也需要尽量小。

请仔细分析仿真结果，并只返回以下 JSON 格式的输出，不要包含任何其他说明文字：
{format_instructions}
"""),
            ("user", """
当前的提示词/任务描述：
{prompt}

仿真最优结果：
{best_result}

请进行反思与判别。
""")
        ])
        
        self.chain = self.prompt | self.llm
        
    async def reflect(self, current_prompt: str, best_result: Dict[str, Any]) -> Dict[str, Any]:
        """
        对仿真结果进行反思，返回判别结果 JSON 结构。
        """
        try:
            logger.info("正在调用 Reflection Agent 进行结果反思...")
            response_msg = await self.chain.ainvoke({
                "prompt": current_prompt,
                "best_result": json.dumps(best_result, ensure_ascii=False, indent=2),
                "format_instructions": self.parser.get_format_instructions()
            })
            
            content = response_msg.content
            
            # Remove <think>...</think> blocks often generated by reasoning models
            import re
            content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()
            
            if content.startswith("```json"):
                content = content[7:-3].strip()
            elif content.startswith("```"):
                content = content[3:-3].strip()
                
            try:
                parsed_response = json.loads(content)
                return parsed_response
            except json.JSONDecodeError:
                # Fallback if json parsing fails but string looks somewhat like dict
                logger.warning(f"Failed to parse JSON natively, trying Langchain Parser. Raw: {content}")
                return self.parser.parse(response_msg.content)
                
        except Exception as e:
            logger.error(f"Reflection Agent 运行出错: {e}")
            # 如果出错，默认不需要进一步优化，避免死循环
            return {"needs_optimization": False, "suggestion": f"反思阶段出错: {e}"}
